### ISSUE TITLE
Cannot access secondary GPU:  [drm] failed to set drm interface version: Permission denied

### ISSUE THREAD

**Issue by kalopsia** [Bumblebee-Project/Bumblebee#580]
I have the common issue. When I try to run something through `optirun`, I get the following:
```
[13395.278406] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) intel(0): [drm] failed to set drm interface version: Permission denied [13].
[13395.278522] [ERROR]Aborting because fallback start is disabled.
```

**Specification:**
- Ubuntu 14.04
- NVIDIA Corporation GF108M [GeForce GT 630M] (rev a1)
- Nvidia 331 driver

I've tried to reinstall nvidia and bumblebee packages, to remove something related with nvidia within `/usr/share/X11/xorg.conf.d`, uncomment BudID in the `xorg.conf.nvidia` file

**optirun -vv --debug bush**
[13077.093918] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[13077.094673] [DEBUG]optirun version 3.2.1 starting...
[13077.094690] [DEBUG]Active configuration:
[13077.094698] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[13077.094705] [DEBUG] X display: :8
[13077.094711] [DEBUG] LD_LIBRARY_PATH: /usr/lib/nvidia-331:/usr/lib32/nvidia-331
[13077.094717] [DEBUG] Socket path: /var/run/bumblebee.socket
[13077.094723] [DEBUG] Accel/display bridge: auto
[13077.094728] [DEBUG] VGL Compression: proxy
[13077.094734] [DEBUG] VGLrun extra options: 
[13077.094740] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus
[13077.094813] [DEBUG]Using auto-detected bridge primus
[13079.358358] [INFO]Response: No - error: [XORG] (EE) intel(0): [drm] failed to set drm interface version: Permission denied [13].
[13079.358418] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) intel(0): [drm] failed to set drm interface version: Permission denied [13].
[13079.358428] [DEBUG]Socket closed.
[13079.358457] [ERROR]Aborting because fallback start is disabled.
[13079.358465] [DEBUG]Killing all remaining processes.

What is wrong?

**Comment by ArchangeGabriel** [comment]
Are there people still facing this issue here with the added section? Can someone for which adding the section solves the issue post Xorg.8.log with and without the section?

Thanks

**Comment by mark-sch** [comment]
Unfortunately latest Debian Jessy has the same DRM issue with Nvidia GF117M, same when using the screen section workaround or not. BusID was necessary to find the card and produce the DRM error (Lenovo Flex-2 14 Ultrabook).

2:00:02.0 VGA compatible controller [0300]: Intel Corporation Haswell-ULT Integrated Graphics Controller [8086:0a16] (rev 09)
16:04:00.0 3D controller [0302]: NVIDIA Corporation GF117M [GeForce 610M/710M/820M / GT 620M/625M/630M/720M] [10de:1140] (rev ff)

**Comment by qazwsxal** [comment]
Using Debian Jessie with a GTX660M, the same issue occurs with or without the "Section "Screen"" fix, BusID not needed.

$ lspci | grep VGA
```
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
01:00.0 VGA compatible controller: NVIDIA Corporation GK107M [GeForce GTX 660M] (rev ff)
```

Xorg.8.log:
```
X.Org X Server 1.16.2.901 (1.16.3 RC 1)
Release Date: 2014-12-09
[ 32638.963] X Protocol Version 11, Revision 0
[ 32638.963] Build Operating System: Linux 3.2.0-4-amd64 x86_64 Debian
[ 32638.963] Current Operating System: Linux Adam-Laptop 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64
[ 32638.963] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-3.16.0-4-amd64 root=UUID=cd2c6929-b062-41c3-a42e-3ac86c02fee8 ro initrd=/install/initrd.gz quiet
[ 32638.963] Build Date: 09 December 2014  10:15:28PM
[ 32638.963] xorg-server 2:1.16.2.901-1 (http://www.debian.org/support) 
[ 32638.963] Current version of pixman: 0.32.6
[ 32638.963] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[ 32638.963] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[ 32638.963] (==) Log file: "/var/log/Xorg.8.log", Time: Tue Jan  6 15:59:02 2015
[ 32638.963] (++) Using config file: "/etc/bumblebee/xorg.conf.nvidia"
[ 32638.963] (++) Using config directory: "/etc/bumblebee/xorg.conf.d"
[ 32638.963] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[ 32638.964] (==) ServerLayout "Layout0"
[ 32638.964] (**) |-->Screen "Default Screen" (0)
[ 32638.964] (**) |   |-->Monitor "<default monitor>"
[ 32638.964] (**) |   |-->Device "DiscreteNvidia"
[ 32638.964] (==) No monitor specified for screen "Default Screen".
	Using a default monitor configuration.
[ 32638.964] (**) Option "AutoAddDevices" "false"
[ 32638.964] (**) Option "AutoAddGPU" "false"
[ 32638.964] (**) Not automatically adding devices
[ 32638.964] (==) Automatically enabling devices
[ 32638.964] (**) Not automatically adding GPU devices
[ 32638.964] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[ 32638.964] 	Entry deleted from font path.
[ 32638.964] (==) FontPath set to:
	/usr/share/fonts/X11/misc,
	/usr/share/fonts/X11/100dpi/:unscaled,
	/usr/share/fonts/X11/75dpi/:unscaled,
	/usr/share/fonts/X11/Type1,
	/usr/share/fonts/X11/100dpi,
	/usr/share/fonts/X11/75dpi,
	built-ins
[ 32638.964] (++) ModulePath set to "/usr/lib/nvidia,/usr/lib/xorg/modules"
[ 32638.964] (==) |-->Input Device "<default pointer>"
[ 32638.964] (==) |-->Input Device "<default keyboard>"
[ 32638.964] (==) The core pointer device wasn't specified explicitly in the layout.
	Using the default mouse configuration.
[ 32638.964] (==) The core keyboard device wasn't specified explicitly in the layout.
	Using the default keyboard configuration.
[ 32638.964] (II) Loader magic: 0x7f688f6f5d80
[ 32638.964] (II) Module ABI versions:
[ 32638.964] 	X.Org ANSI C Emulation: 0.4
[ 32638.964] 	X.Org Video Driver: 18.0
[ 32638.964] 	X.Org XInput driver : 21.0
[ 32638.964] 	X.Org Server Extension : 8.0
[ 32638.964] (II) xfree86: Adding drm device (/dev/dri/card1)
[ 32638.965] (II) xfree86: Adding drm device (/dev/dri/card0)
[ 32638.965] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
[ 32638.966] (--) PCI:*(0:1:0:0) 10de:0fd4:1558:3700 rev 161, Mem @ 0xf6000000/16777216, 0xe0000000/268435456, 0xf0000000/33554432, I/O @ 0x0000e000/128, BIOS @ 0x????????/524288
[ 32638.966] (II) LoadModule: "glx"
[ 32638.966] (II) Loading /usr/lib/nvidia/current/libglx.so
[ 32638.978] (II) Module glx: vendor="NVIDIA Corporation"
[ 32638.978] 	compiled for 4.0.2, module version = 1.0.0
[ 32638.978] 	Module class: X.Org Server Extension
[ 32638.978] (II) NVIDIA GLX Module  340.65  Tue Dec  2 09:10:06 PST 2014
[ 32638.978] (II) LoadModule: "nvidia"
[ 32638.978] (II) Loading /usr/lib/nvidia/nvidia_drv.so
[ 32638.979] (II) Module nvidia: vendor="NVIDIA Corporation"
[ 32638.979] 	compiled for 4.0.2, module version = 1.0.0
[ 32638.979] 	Module class: X.Org Video Driver
[ 32638.979] (II) LoadModule: "mouse"
[ 32638.979] (II) Loading /usr/lib/xorg/modules/input/mouse_drv.so
[ 32638.979] (II) Module mouse: vendor="X.Org Foundation"
[ 32638.979] 	compiled for 1.16.1, module version = 1.9.1
[ 32638.979] 	Module class: X.Org XInput Driver
[ 32638.979] 	ABI class: X.Org XInput driver, version 21.0
[ 32638.979] (II) LoadModule: "kbd"
[ 32638.979] (WW) Warning, couldn't open module kbd
[ 32638.979] (II) UnloadModule: "kbd"
[ 32638.979] (II) Unloading kbd
[ 32638.979] (EE) Failed to load module "kbd" (module does not exist, 0)
[ 32638.979] (II) NVIDIA dlloader X Driver  340.65  Tue Dec  2 08:47:36 PST 2014
[ 32638.979] (II) NVIDIA Unified Driver for all Supported NVIDIA GPUs
[ 32638.980] (--) using VT number 7

[ 32638.980] (II) Loading sub module "fb"
[ 32638.980] (II) LoadModule: "fb"
[ 32638.980] (II) Loading /usr/lib/xorg/modules/libfb.so
[ 32638.980] (II) Module fb: vendor="X.Org Foundation"
[ 32638.980] 	compiled for 1.16.2.901, module version = 1.0.0
[ 32638.980] 	ABI class: X.Org ANSI C Emulation, version 0.4
[ 32638.980] (WW) Unresolved symbol: fbGetGCPrivateKey
[ 32638.980] (II) Loading sub module "wfb"
[ 32638.980] (II) LoadModule: "wfb"
[ 32638.980] (II) Loading /usr/lib/xorg/modules/libwfb.so
[ 32638.980] (II) Module wfb: vendor="X.Org Foundation"
[ 32638.980] 	compiled for 1.16.2.901, module version = 1.0.0
[ 32638.980] 	ABI class: X.Org ANSI C Emulation, version 0.4
[ 32638.980] (II) Loading sub module "ramdac"
[ 32638.980] (II) LoadModule: "ramdac"
[ 32638.980] (II) Module "ramdac" already built-in
[ 32638.981] (II) NVIDIA(0): Creating default Display subsection in Screen section
	"Default Screen" for depth/fbbpp 24/32
[ 32638.981] (==) NVIDIA(0): Depth 24, (==) framebuffer bpp 32
[ 32638.981] (==) NVIDIA(0): RGB weight 888
[ 32638.981] (==) NVIDIA(0): Default visual is TrueColor
[ 32638.981] (==) NVIDIA(0): Using gamma correction (1.0, 1.0, 1.0)
[ 32638.981] (**) NVIDIA(0): Option "NoLogo" "true"
[ 32638.981] (**) NVIDIA(0): Option "ProbeAllGpus" "false"
[ 32638.981] (**) NVIDIA(0): Option "UseEDID" "false"
[ 32638.981] (**) NVIDIA(0): Option "UseDisplayDevice" "none"
[ 32638.981] (**) NVIDIA(0): Enabling 2D acceleration
[ 32638.981] (**) NVIDIA(0): Ignoring EDIDs
[ 32638.981] (**) NVIDIA(0): Option "UseDisplayDevice" set to "none"; enabling NoScanout
[ 32638.981] (**) NVIDIA(0):     mode
[ 32647.899] (EE) NVIDIA(GPU-0): Failed to initialize the NVIDIA GPU at PCI:1:0:0.  Please
[ 32647.899] (EE) NVIDIA(GPU-0):     check your system's kernel log for additional error
[ 32647.899] (EE) NVIDIA(GPU-0):     messages and refer to Chapter 8: Common Problems in the
[ 32647.899] (EE) NVIDIA(GPU-0):     README for additional information.
[ 32647.899] (EE) NVIDIA(GPU-0): Failed to initialize the NVIDIA graphics device!
[ 32647.899] (EE) NVIDIA(0): Failing initialization of X screen 0
[ 32647.899] (II) UnloadModule: "nvidia"
[ 32647.899] (II) UnloadSubModule: "wfb"
[ 32647.899] (II) UnloadSubModule: "fb"
[ 32647.899] (EE) Screen(s) found, but none have a usable configuration.
[ 32647.899] (EE) 
Fatal server error:
[ 32647.899] (EE) no screens found(EE) 
[ 32647.899] (EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[ 32647.899] (EE) Please also check the log file at "/var/log/Xorg.8.log" for additional information.
[ 32647.899] (EE) 
[ 32647.899] (EE) Server terminated with error (1). Closing log file.
```

**Comment by qazwsxal** [comment]
optirun glxgears
```
[ 1364.758325] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied

[ 1364.758356] [ERROR]Aborting because fallback start is disabled.
```

dmesg
```
[ 1351.165056] bbswitch: enabling discrete graphics
[ 1353.304608] nvidia: module license 'NVIDIA' taints kernel.
[ 1353.304614] Disabling lock debugging due to kernel taint
[ 1353.319265] vgaarb: device changed decodes: PCI:0000:01:00.0,olddecodes=io+mem,decodes=none:owns=none
[ 1353.319807] [drm] Initialized nvidia-drm 0.0.0 20130102 for 0000:01:00.0 on minor 1
[ 1353.319823] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  340.65  Tue Dec  2 09:50:34 PST 2014
[ 1355.182781] nvidia 0000:01:00.0: irq 49 for MSI/MSI-X
[ 1355.188208] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[ 1355.188322] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[ 1355.188386] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[ 1355.188444] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[ 1355.188500] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[ 1355.188555] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[ 1355.188643] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[ 1355.188699] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[ 1359.751231] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[ 1364.034866] NVRM: RmInitAdapter failed! (0x25:0x28:1197)
[ 1364.034874] NVRM: rm_init_adapter failed for device bearing minor number 0
[ 1364.034894] NVRM: nvidia_frontend_open: minor 0, module->open() failed, error -5
```

**Comment by falseidols** [comment]
I was getting the same error (just started recently). I tried the screen section fix above to no avail. The only other thing I changed on my system since was shutting off ipv6 at boot (for an unrelated issue with apt being slow/timing out), and everything started working again. Not sure why, but it worked.

**Comment by ArchangeGabriel** [comment]
@falseidols Could you try reenabling ipv6 at boot and try again? I want to know wether anyone is still having this bug in any situation.

@mark-sch Could you provide all the asked logs?

**Comment by Lotus907efi** [comment]
Having the same problem here on a HP Zbook15 with Intel IGA and NVidia GK106GLM [Quadro K2100M] (rev a1) on Ubuntu 14.04 64bit. I m trying to use the nouveau drivers but I did make the mistake of using the Intel Graphics Installer to update things. It installed a LOT of stuff and I am worried that if I try to purge the i915 driver, it seems like it will leave almost all of the rest of the intel installed packages. I don't want to completely hose my system since I use this for work. At least right now I am still able to use the laptop display at 1920x1080.

**Comment by ArchangeGabriel** [comment]
@Lotus907efi Sorry for the delay, are you still having troubles here? If not and if no one else answers here, I will consider closing this issue.

**Comment by AlexCzar** [comment]
I have the same (or very similar issue) on OpenSUSE 13.2 x86_64
Kernel: `3.18.6-1.gec2a744-desktop`

```
rpm -qi bumblebee
Name        : bumblebee
Version     : 3.2.1
Release     : 20.1
Architecture: x86_64
```

**Comment by Alpherie** [comment]
Had the same problem on Debian Jessie. Fixed it by completely purging all nvidia drivears and bumblebee packages and the reinstalling them. The nvidia-driver installed is now 340 (do not remember what it was before.)

The important thing - after reinstallation it throwed out the same problem, but according to @merkur04 I deleted all BusID mentions in config files and emptied /etc/bumblebee/xorg.conf.d/
Then it worked! 

Though I get less framerate at glxgears with optirun (250) then without (500), but the problem in topic was solved.

**Comment by AlexCzar** [comment]
I chose to revert to nvidia driver which does not have problems on my system as of now (v346.35)

**Comment by ArchangeGabriel** [comment]
@AlexCzar nouveau is very different, specially on OSes running latest versions of X.org, kernel, etc.

You might open a new issue if you want for this one, the fact is you’re probably having troubles because of PRIME taking precedence.

I’m closing this issue since no one seems to be affected by a real bug here.

**Comment by mingjunyang** [comment]
openSUSE13.2 kernel 3.16.7-13-desktop gnome 3.14.0
```
 sudo lspci -vnn | grep '\''[030[02]\]'
00:02.0 VGA compatible controller [0300]: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller [8086:0416] (rev 06) (prog-if 00 [VGA controller])
01:00.0 3D controller [0302]: NVIDIA Corporation GM107M [GeForce GTX 860M] [10de:1392] (rev a2)
```
```
optirun -vv --debug bush
[ 1323.850875] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[ 1323.851138] [DEBUG]optirun version 3.2.1 starting...
[ 1323.851151] [DEBUG]Active configuration:
[ 1323.851156] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[ 1323.851161] [DEBUG] X display: :8
[ 1323.851166] [DEBUG] LD_LIBRARY_PATH: 
[ 1323.851170] [DEBUG] Socket path: /var/run/bumblebee.socket
[ 1323.851175] [DEBUG] Accel/display bridge: auto
[ 1323.851180] [DEBUG] VGL Compression: proxy
[ 1323.851184] [DEBUG] VGLrun extra options: 
[ 1323.851189] [DEBUG] Primus LD Path: /usr/lib64/primus:/usr/lib/primus
[ 1323.851211] [DEBUG]Using auto-detected bridge virtualgl
[ 1323.856806] [INFO]Response: No - error: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied

[ 1323.856832] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied

[ 1323.856837] [DEBUG]Socket closed.
[ 1323.856847] [ERROR]Aborting because fallback start is disabled.
[ 1323.856854] [DEBUG]Killing all remaining processes.

```
I add the code to /etc/bumblebee/xorg.conf.nvidia
```
Section "Screen"
    Identifier "Default Screen"
    Device "DiscreteNvidia"
EndSection

```
but it didnot work.....

**Comment by Nargren** [comment]
I am also getting this error on OpenSUSE 13.2, kernel 3.16.7-7-desktop, KDE environment.

lspci
`00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
01:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 840M] (rev a2)`

optirun -vv --debug bush
`[  872.676248] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[  872.676537] [DEBUG]optirun version 3.2.1 starting...
[  872.676546] [DEBUG]Active configuration:
[  872.676550] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[  872.676554] [DEBUG] X display: :8
[  872.676558] [DEBUG] LD_LIBRARY_PATH: 
[  872.676561] [DEBUG] Socket path: /var/run/bumblebee.socket
[  872.676564] [DEBUG] Accel/display bridge: auto
[  872.676566] [DEBUG] VGL Compression: proxy
[  872.676568] [DEBUG] VGLrun extra options: 
[  872.676570] [DEBUG] Primus LD Path: /usr/lib64/primus:/usr/lib/primus
[  872.676594] [DEBUG]Using auto-detected bridge virtualgl
[  872.684014] [INFO]Response: No - error: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
[  872.684030] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
[  872.684034] [DEBUG]Socket closed.
[  872.684046] [ERROR]Aborting because fallback start is disabled.
[  872.684050] [DEBUG]Killing all remaining processes.`

**Comment by ArchangeGabriel** [comment]
@Nargren @mingjunyang Can you open a new (one for both of you) issue and post Xorg.8.log and dmesg output there (or in a gist)? Thanks.

**Comment by mingjunyang** [comment]
@ArchangeGabriel  I format my os and reinstall opensuse 13.2,update to now . and I install the bumblebee,it's works.
DId you want to see this ```bumblebee-bugreport-20150416_175034.tar.gz```.this file created by the ```bumblebee-bugreport``` ,when it not work.
我的英文好low（my english so low ），我用中文重新描述一遍（我认为这样对与我们交流可能有帮助）。我格式化掉 / 分区以后，重装了opensuse13.2,并更新到最新,然后重新安装了bumblebee，它就正常工作了。
在出现那个问题的时候我用```bumblebee-bugreport```创建了一份报告```bumblebee-bugreport-20150416_175034.tar.gz``。

**Comment by ArchangeGabriel** [comment]
No, if reinstall fixed it, that means it was a config issue, so bugreport
isn’t needed.

**Comment by MrHalfman** [comment]
Hi, I have the same issue under Ubuntu 15.04.

```
$ dkms status                                   
bbswitch, 0.7, 3.19.0-15-generic, x86_64: installed
nvidia-346, 346.59, 3.19.0-15-generic, x86_64: installed
vboxhost, 4.3.16, 3.13.0-37-generic, x86_64: installed
vboxhost, 4.3.16, 3.16.0-22-generic, x86_64: installed
vboxhost, 4.3.16, 3.16.0-34-generic, x86_64: installed
vboxhost, 4.3.16, 3.19.0-15-generic, x86_64: installed
```

```
$ optirun -vv glxgears -info                    
[ 1273.947005] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[ 1273.947404] [INFO]Configured driver: nvidia
[ 1273.947607] [DEBUG]optirun version 3.2.1 starting...
[ 1273.947650] [DEBUG]Active configuration:
[ 1273.947669] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[ 1273.947688] [DEBUG] X display: :8
[ 1273.947706] [DEBUG] LD_LIBRARY_PATH: /usr/lib/nvidia-346:/usr/lib32/nvidia-346
[ 1273.947724] [DEBUG] Socket path: /var/run/bumblebee.socket
[ 1273.947743] [DEBUG] Accel/display bridge: auto
[ 1273.947762] [DEBUG] VGL Compression: proxy
[ 1273.947781] [DEBUG] VGLrun extra options: 
[ 1273.947799] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus
[ 1273.947870] [DEBUG]Using auto-detected bridge primus
[ 1276.196889] [INFO]Response: No - error: [XORG] (EE) No devices detected.

[ 1276.196916] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) No devices detected.

[ 1276.196923] [DEBUG]Socket closed.
[ 1276.196952] [ERROR]Aborting because fallback start is disabled.
[ 1276.196963] [DEBUG]Killing all remaining processes.
```

```
$ lspci
VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
VGA compatible controller: NVIDIA Corporation GF108M [GeForce GT 635M] (rev a1)
```

```
$ uname -srv
Linux 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015
```
I also have this in my logs :
```
[ 1654.149545] [ERROR][XORG] (EE) intel(0): [drm] failed to set drm interface version: Permission denied [13].
[ 1654.149558] [ERROR][XORG] (EE) intel(0): Failed to claim DRM device.
[ 1654.149566] [ERROR][XORG] (EE) Screen(s) found, but none have a usable configuration.
[ 1654.149574] [ERROR][XORG] (EE)
[ 1654.149581] [ERROR][XORG] (EE) no screens found(EE)
[ 1654.149589] [ERROR][XORG] (EE)
[ 1654.149601] [ERROR][XORG] (EE) Please also check the log file at "/var/log/Xorg.8.log" for additional information.
[ 1654.149609] [ERROR][XORG] (EE)
[ 1654.149619] [ERROR][XORG] (EE) Server terminated with error (1). Closing log file.
[ 1654.154051] [ERROR]X did not start properly
```

I tried to add the Section given by @merkur04 but it doesn't change anything and I can't reinstall my system as for now :unamused:. 

Tell me if you want more informations. Thanks for your help.

**Comment by michalzubkowicz** [comment]
For a few days I have this problem on Ubuntu 14.04, tried downgrading backports, changing driver from 331 to 331-updates.

**Comment by Kuzirashi** [comment]
I'm also encountering this error but I don't have bumblebee...

**Comment by dawidm** [comment]
I have this problem on Debian Jessie (nvidia driver version 340.65-2, bumblebee 3.2.1-7).
Xorg.8.log:
```
[ 20872.500] 
X.Org X Server 1.16.4
Release Date: 2014-12-20
[ 20872.500] X Protocol Version 11, Revision 0
[ 20872.500] Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
[ 20872.500] Current Operating System: Linux dawid-laptop 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u4 (2015-09-19) x86_64
[ 20872.500] Kernel command line: BOOT_IMAGE=/vmlinuz-3.16.0-4-amd64 root=UUID=a2f3b2a9-b796-46ee-966c-b6cf53a54a83 ro quiet splash
[ 20872.500] Build Date: 11 February 2015  12:32:02AM
[ 20872.500] xorg-server 2:1.16.4-1 (http://www.debian.org/support) 
[ 20872.500] Current version of pixman: 0.32.6
[ 20872.500]    Before reporting problems, check http://wiki.x.org
    to make sure that you have the latest version.
[ 20872.500] Markers: (--) probed, (**) from config file, (==) default setting,
    (++) from command line, (!!) notice, (II) informational,
    (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[ 20872.500] (==) Log file: "/var/log/Xorg.8.log", Time: Tue Oct  6 22:47:56 2015
[ 20872.500] (++) Using config file: "/etc/bumblebee/xorg.conf.nvidia"
[ 20872.500] (EE) Unable to locate/open config directory: "/etc/bumblebee/xorg.conf.d"
[ 20872.500] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[ 20872.501] (==) ServerLayout "Layout0"
[ 20872.501] (**) |-->Screen "Default Screen" (0)
[ 20872.501] (**) |   |-->Monitor "<default monitor>"
[ 20872.501] (**) |   |-->Device "DiscreteNvidia"
[ 20872.501] (==) No monitor specified for screen "Default Screen".
    Using a default monitor configuration.
[ 20872.501] (**) Option "AutoAddDevices" "false"
[ 20872.501] (**) Option "AutoAddGPU" "false"
[ 20872.501] (**) Not automatically adding devices
[ 20872.501] (==) Automatically enabling devices
[ 20872.501] (**) Not automatically adding GPU devices
[ 20872.501] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[ 20872.501]    Entry deleted from font path.
[ 20872.501] (==) FontPath set to:
    /usr/share/fonts/X11/misc,
    /usr/share/fonts/X11/100dpi/:unscaled,
    /usr/share/fonts/X11/75dpi/:unscaled,
    /usr/share/fonts/X11/Type1,
    /usr/share/fonts/X11/100dpi,
    /usr/share/fonts/X11/75dpi,
    built-ins
[ 20872.501] (++) ModulePath set to "/usr/lib/nvidia,/usr/lib/xorg/modules"
[ 20872.501] (==) |-->Input Device "<default pointer>"
[ 20872.501] (==) |-->Input Device "<default keyboard>"
[ 20872.501] (==) The core pointer device wasn't specified explicitly in the layout.
    Using the default mouse configuration.
[ 20872.501] (==) The core keyboard device wasn't specified explicitly in the layout.
    Using the default keyboard configuration.
[ 20872.501] (II) Loader magic: 0x7f6fa0ce3d80
[ 20872.501] (II) Module ABI versions:
[ 20872.501]    X.Org ANSI C Emulation: 0.4
[ 20872.501]    X.Org Video Driver: 18.0
[ 20872.501]    X.Org XInput driver : 21.0
[ 20872.501]    X.Org Server Extension : 8.0
[ 20872.501] (II) xfree86: Adding drm device (/dev/dri/card1)
[ 20872.501] (II) xfree86: Adding drm device (/dev/dri/card0)
[ 20872.501] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
[ 20872.502] (--) PCI:*(0:1:0:0) 10de:0df4:144d:c0a5 rev 161, Mem @ 0xf4000000/16777216, 0xd0000000/268435456, 0xe0000000/33554432, I/O @ 0x0000d000/128, BIOS @ 0x????????/524288
[ 20872.502] (II) LoadModule: "glx"
[ 20872.502] (II) Loading /usr/lib/nvidia/libglx.so
[ 20872.509] (II) Module glx: vendor="NVIDIA Corporation"
[ 20872.509]    compiled for 4.0.2, module version = 1.0.0
[ 20872.509]    Module class: X.Org Server Extension
[ 20872.509] (II) NVIDIA GLX Module  340.65  Tue Dec  2 09:10:06 PST 2014
[ 20872.509] (II) LoadModule: "nvidia"
[ 20872.509] (II) Loading /usr/lib/nvidia/nvidia_drv.so
[ 20872.510] (II) Module nvidia: vendor="NVIDIA Corporation"
[ 20872.510]    compiled for 4.0.2, module version = 1.0.0
[ 20872.510]    Module class: X.Org Video Driver
[ 20872.510] (II) LoadModule: "mouse"
[ 20872.510] (II) Loading /usr/lib/xorg/modules/input/mouse_drv.so
[ 20872.510] (II) Module mouse: vendor="X.Org Foundation"
[ 20872.510]    compiled for 1.16.1, module version = 1.9.1
[ 20872.510]    Module class: X.Org XInput Driver
[ 20872.510]    ABI class: X.Org XInput driver, version 21.0
[ 20872.510] (II) LoadModule: "kbd"
[ 20872.510] (WW) Warning, couldn't open module kbd
[ 20872.510] (II) UnloadModule: "kbd"
[ 20872.510] (II) Unloading kbd
[ 20872.510] (EE) Failed to load module "kbd" (module does not exist, 0)
[ 20872.510] (II) NVIDIA dlloader X Driver  340.65  Tue Dec  2 08:47:36 PST 2014
[ 20872.510] (II) NVIDIA Unified Driver for all Supported NVIDIA GPUs
[ 20872.510] (--) using VT number 7

[ 20872.510] (II) Loading sub module "fb"
[ 20872.510] (II) LoadModule: "fb"
[ 20872.511] (II) Loading /usr/lib/xorg/modules/libfb.so
[ 20872.511] (II) Module fb: vendor="X.Org Foundation"
[ 20872.511]    compiled for 1.16.4, module version = 1.0.0
[ 20872.511]    ABI class: X.Org ANSI C Emulation, version 0.4
[ 20872.511] (WW) Unresolved symbol: fbGetGCPrivateKey
[ 20872.511] (II) Loading sub module "wfb"
[ 20872.511] (II) LoadModule: "wfb"
[ 20872.511] (II) Loading /usr/lib/xorg/modules/libwfb.so
[ 20872.511] (II) Module wfb: vendor="X.Org Foundation"
[ 20872.511]    compiled for 1.16.4, module version = 1.0.0
[ 20872.511]    ABI class: X.Org ANSI C Emulation, version 0.4
[ 20872.511] (II) Loading sub module "ramdac"
[ 20872.511] (II) LoadModule: "ramdac"
[ 20872.511] (II) Module "ramdac" already built-in
[ 20872.511] (II) NVIDIA(0): Creating default Display subsection in Screen section
    "Default Screen" for depth/fbbpp 24/32
[ 20872.511] (==) NVIDIA(0): Depth 24, (==) framebuffer bpp 32
[ 20872.511] (==) NVIDIA(0): RGB weight 888
[ 20872.511] (==) NVIDIA(0): Default visual is TrueColor
[ 20872.511] (==) NVIDIA(0): Using gamma correction (1.0, 1.0, 1.0)
[ 20872.511] (**) NVIDIA(0): Option "NoLogo" "true"
[ 20872.511] (**) NVIDIA(0): Option "ProbeAllGpus" "false"
[ 20872.511] (**) NVIDIA(0): Option "UseEDID" "false"
[ 20872.511] (**) NVIDIA(0): Option "UseDisplayDevice" "none"
[ 20872.511] (**) NVIDIA(0): Enabling 2D acceleration
[ 20872.511] (**) NVIDIA(0): Ignoring EDIDs
[ 20872.511] (**) NVIDIA(0): Option "UseDisplayDevice" set to "none"; enabling NoScanout
[ 20872.511] (**) NVIDIA(0):     mode
[ 20875.999] (II) NVIDIA(GPU-0): Found DRM driver nvidia-drm (20130102)
[ 20875.999] (II) NVIDIA(0): NVIDIA GPU GeForce GT 540M (GF108) at PCI:1:0:0 (GPU-0)
[ 20875.999] (--) NVIDIA(0): Memory: 1048576 kBytes
[ 20875.999] (--) NVIDIA(0): VideoBIOS: 70.08.58.00.03
[ 20875.999] (II) NVIDIA(0): Detected PCI Express Link width: 16X
[ 20875.999] (--) NVIDIA(0): Valid display device(s) on GeForce GT 540M at PCI:1:0:0
[ 20875.999] (--) NVIDIA(0):     none
[ 20875.999] (II) NVIDIA(0): Validated MetaModes:
[ 20875.999] (II) NVIDIA(0):     "NULL"
[ 20875.999] (II) NVIDIA(0): Virtual screen size determined to be 640 x 480
[ 20875.999] (WW) NVIDIA(0): Unable to get display device for DPI computation.
[ 20875.999] (==) NVIDIA(0): DPI set to (75, 75); computed from built-in default
[ 20875.999] (--) Depth 24 pixmap format is 32 bpp
[ 20875.999] (II) NVIDIA: Using 3072.00 MB of virtual memory for indirect memory
[ 20875.999] (II) NVIDIA:     access.
[ 20876.002] (II) NVIDIA(0): Setting mode "NULL"
[ 20876.014] (==) NVIDIA(0): Disabling shared memory pixmaps
[ 20876.014] (==) NVIDIA(0): Backing store enabled
[ 20876.014] (==) NVIDIA(0): Silken mouse enabled
[ 20876.015] (==) NVIDIA(0): DPMS enabled
[ 20876.015] (II) Loading sub module "dri2"
[ 20876.015] (II) LoadModule: "dri2"
[ 20876.015] (II) Module "dri2" already built-in
[ 20876.015] (II) NVIDIA(0): [DRI2] Setup complete
[ 20876.015] (II) NVIDIA(0): [DRI2]   VDPAU driver: nvidia
[ 20876.015] (--) RandR disabled
[ 20876.018] (II) SELinux: Disabled on system
[ 20876.019] (II) Initializing extension GLX
[ 20876.019] (II) Indirect GLX disabled.(II) Using input driver 'mouse' for '<default pointer>'
[ 20876.050] (**) Option "CorePointer" "on"
[ 20876.050] (**) <default pointer>: always reports core events
[ 20876.050] (WW) <default pointer>: No Device specified, looking for one...
[ 20876.136] (II) <default pointer>: Setting Device option to "/dev/input/mice"
[ 20876.136] (--) <default pointer>: Device: "/dev/input/mice"
[ 20876.136] (==) <default pointer>: Protocol: "Auto"
[ 20876.136] (**) <default pointer>: always reports core events
[ 20876.136] (**) Option "Device" "/dev/input/mice"
[ 20876.212] (==) <default pointer>: Emulate3Buttons, Emulate3Timeout: 50
[ 20876.212] (**) <default pointer>: ZAxisMapping: buttons 4 and 5
[ 20876.212] (**) <default pointer>: Buttons: 9
[ 20876.212] (II) XINPUT: Adding extended input device "<default pointer>" (type: MOUSE, id 6)
[ 20876.212] (**) <default pointer>: (accel) keeping acceleration scheme 1
[ 20876.212] (**) <default pointer>: (accel) acceleration profile 0
[ 20876.212] (**) <default pointer>: (accel) acceleration factor: 2.000
[ 20876.212] (**) <default pointer>: (accel) acceleration threshold: 4
[ 20876.212] (II) <default pointer>: Setting mouse protocol to "ExplorerPS/2"
[ 20876.506] (II) <default pointer>: ps2EnableDataReporting: succeeded
[ 20876.506] (II) LoadModule: "kbd"
[ 20876.506] (WW) Warning, couldn't open module kbd
[ 20876.506] (II) UnloadModule: "kbd"
[ 20876.506] (II) Unloading kbd
[ 20876.506] (EE) Failed to load module "kbd" (module does not exist, 0)
[ 20876.506] (EE) No input driver matching `kbd'
[ 20876.507] (II) config/udev: Adding input device Power Button (/dev/input/event4)
[ 20876.507] (II) AutoAddDevices is off - not adding device.
[ 20876.507] (II) config/udev: Adding input device Video Bus (/dev/input/event8)
[ 20876.507] (II) AutoAddDevices is off - not adding device.
[ 20876.507] (II) config/udev: Adding input device Video Bus (/dev/input/event7)
[ 20876.507] (II) AutoAddDevices is off - not adding device.
[ 20876.507] (II) config/udev: Adding input device Power Button (/dev/input/event2)
[ 20876.507] (II) AutoAddDevices is off - not adding device.
[ 20876.507] (II) config/udev: Adding input device Lid Switch (/dev/input/event1)
[ 20876.507] (II) AutoAddDevices is off - not adding device.
[ 20876.508] (II) config/udev: Adding input device Sleep Button (/dev/input/event3)
[ 20876.508] (II) AutoAddDevices is off - not adding device.
[ 20876.508] (II) config/udev: Adding drm device (/dev/dri/card0)
[ 20876.508] (II) xfree86: Adding drm device (/dev/dri/card0)
[ 20876.508] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
[ 20876.508] (II) config/udev: Adding input device WebCam SCB-1100N (/dev/input/event14)
[ 20876.508] (II) AutoAddDevices is off - not adding device.
[ 20876.508] (II) config/udev: Adding input device HDA Intel PCH Mic (/dev/input/event11)
[ 20876.508] (II) AutoAddDevices is off - not adding device.
[ 20876.508] (II) config/udev: Adding input device HDA Intel PCH Headphone (/dev/input/event12)
[ 20876.508] (II) AutoAddDevices is off - not adding device.
[ 20876.508] (II) config/udev: Adding input device HDA Intel PCH HDMI/DP,pcm=3 (/dev/input/event13)
[ 20876.508] (II) AutoAddDevices is off - not adding device.
[ 20876.508] (II) config/udev: Adding input device 2.4G Wireless Keyboard&Mouse (/dev/input/event5)
[ 20876.509] (II) AutoAddDevices is off - not adding device.
[ 20876.509] (II) config/udev: Adding input device 2.4G Wireless Keyboard&Mouse (/dev/input/event6)
[ 20876.509] (II) AutoAddDevices is off - not adding device.
[ 20876.509] (II) config/udev: Adding input device 2.4G Wireless Keyboard&Mouse (/dev/input/mouse0)
[ 20876.509] (II) AutoAddDevices is off - not adding device.
[ 20876.509] (II) config/udev: Adding input device AT Translated Set 2 keyboard (/dev/input/event0)
[ 20876.509] (II) AutoAddDevices is off - not adding device.
[ 20876.509] (II) config/udev: Adding input device ETPS/2 Elantech Touchpad (/dev/input/event10)
[ 20876.509] (II) AutoAddDevices is off - not adding device.
[ 20876.509] (II) config/udev: Adding input device ETPS/2 Elantech Touchpad (/dev/input/mouse1)
[ 20876.509] (II) AutoAddDevices is off - not adding device.
[ 20876.509] (II) config/udev: Adding input device PC Speaker (/dev/input/event9)
[ 20876.509] (II) AutoAddDevices is off - not adding device.
[ 20893.452] (II) UnloadModule: "mouse"
[ 20893.471] (II) NVIDIA(GPU-0): Deleting GPU-0
[ 20893.472] (EE) Server terminated successfully (0). Closing log file.
```
Fragment of dmesg:
```
[19253.614825] [drm] Initialized nvidia-drm 0.0.0 20130102 for 0000:01:00.0 on minor 1
[19253.614830] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  340.65  Tue Dec  2 09:50:34 PST 2014
[19253.629500] vgaarb: this pci device is not a vga device
[19253.629967] nvidia 0000:01:00.0: irq 51 for MSI/MSI-X
[19253.632138] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[19253.632191] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[19253.632219] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[19253.632245] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[19253.632281] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[19253.632307] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[19253.632343] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[19253.632368] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[19257.509421] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[19257.908744] vgaarb: this pci device is not a vga device
[19298.336278] [drm] Module unloaded
[19298.338047] bbswitch: disabling discrete graphics
[19298.338059] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
[19298.350782] pci 0000:01:00.0: Refused to change power state, currently in D0
```

**Comment by bremme** [comment]
I also had this problem on a fresh install of Debian Jessie. My dedicated GPU is a GeForce GT 650M. I tried pretty much all of the recommended fixes. 

Appending to /etc/bumblebee/xorg.conf.nvidia:

```
Section "Screen"
    Identifier "Default Screen"
    Device "DiscreteNvidia"
EndSection
```

Uncommenting and commenting `BusID "PCI:01:00:0"` in /etc/bumblebee/xorg.conf.nvidia.

Downgrading the following packages from `2.4.58` to `2.4.56`:
```
libdrm2
libdrm-dev
libdrm-intel1
libdrm-nouveau2
libdrm-radeon1
```

But nothing worked, kept getting the `ERROR]Cannot access secondary GPU - error: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied` error.

Finally I tried altering /etc/default/grub by adding an additional command line switch (as described here: https://bbs.archlinux.org/viewtopic.php?id=169742):

`GRUB_CMDLINE_LINUX_DEFAULT="quiet rcutree.rcu_idle_gp_delay=1"` (don' t forget to update grub)

Finally: 
```
vblank_mode=0 optirun -vv glxgears -info
13405 frames in 5.0 seconds = 2680.953 FPS
```

**Comment by mamantoha** [comment]
Thanks @jkwong888. It's works for me on Ubuntu 15.10.

**Comment by ArchangeGabriel** [comment]
On kernel version lower than 3.19 you indeed need the `rcutree.rcu_idle_gp_delay=1` kernel parameter. No longer needed as of 3.19.

**Comment by aerique** [comment]
Since this issue and #580 are some of the top Google hits (even the Arch Wiki links to #580 ) for the permission denied issues I'm going to write down my solution for Debian Jessie: downgrade to libdrm*_2.4.56 which can be gotten here http://snapshot.debian.org/archive/debian/20140810T163814Z/pool/main/libd/libdrm/

I downgraded all libdrm* packages I had installed which were, from memory: libdrm-intel1, libdrm-nouveau2, libdrm-radeon1 and libdrm2.

**Comment by ArchangeGabriel** [comment]
@aerique What is this solving? You’re having optirun not working with newer version of libdrm or is it only this message that scares you and you want to make disappear?

**Comment by aerique** [comment]
@ArchangeGabriel I'm sorry I should have mentioned that as well. optirun did indeed not work (for example with glxgears, glxspheres or Steam) and now it does :-)

**Comment by ArchangeGabriel** [comment]
@aerique Well then please open a new bug report with log in both cases.

**Comment by pik** [comment]
Hello, I'm having this same problem when I've used acpi_call to disable my GPU and then turn it back on again.

**Comment by louisgv** [comment]
I solved this problem by setting my driver manually, thanks to this  s.o answer's suggestion: http://askubuntu.com/questions/450467/ubuntu-14-04-nvidia-optimus-bumblebee-error

Since I'm using Nvidia proprietary driver, I'm using 367. But in your case, just search `/usr/lib/nvidia-***` to find your version. Then in your '/etc/bumblebee/bumblebee.conf', set it up using that path/version:

```
Driver=nvidia

...

[driver-nvidia]
KernelDriver=nvidia-367
LibraryPath=/usr/lib/nvidia-367:/usr/lib32/nvidia-367
XorgModulePath=/usr/lib/nvidia-367/xorg,/usr/lib/xorg/modules
```

**Comment by Chronos2011** [comment]
Thanks to @bremme , I finally got rid of the issue as well. As with him, none of the other suggestions fixed my Debian Jessie running a Geforce GT 650M / "Intel Corporation 3rd Gen Core processor Graphics Controller", but applying `GRUB_CMDLINE_LINUX_DEFAULT="quiet rcutree.rcu_idle_gp_delay=1"` in `/etc/default/grub`.
Interestingly, after applying the fix, another issue (the GPU fan running wildly) was fixed as well.

I have
 * libdrm2:amd64 2.4.58-2
 * bumblebee 3.2.1-7
 * bumblebee-nvidia 3.2.1-7
 * nvidia-driver 340.101-1

**Comment by pet89** [comment]
little angel, you're closing the issue but it is the first google result for "failed set drm cannot access secondary GPU" ... you're very embarassed by other conditions than
Ubuntu 14.04
NVIDIA Corporation GF108M [GeForce GT 630M](rev a1)
Nvidia 331 driver
ah i understand little angel computers are like biological systems, we have to calm down the patients :)

**Comment by drgr33n** [comment]
Try this.
RUN sudo update-glx --config glx

and choose /usr/lib/nvidia/bumblebee in auto mode

**Comment by RobKehl** [comment]
@drgr33n That was it on my Debian 9.3 (Stretch) with a rather old Nvidia GT 630M (Optimus) driven by the 475 stable Debian nvidia non-free packages - thanks a lot!

**Comment by someonewithpc** [comment]
Still having this error on Arch Linux with a 960M. Tried adding to the xorg config as mentioned above, but still have the same error in the log. However, `optirun glxinfo | fgrep -i opengl` does show the nvidia info. (My problem is video acceleration isn't working, thought this might be related)
