### ISSUE TITLE
GT650M:  Failed to initialize the NVIDIA GPU at PCI:1:0:0  (kernel configuration bug)

### ISSUE THREAD

**Issue by silverdev** [Bumblebee-Project/Bumblebee#615]
Hello everyone I have been trying one and off to get bumbee to work on my computer for half a year. I have x11-drivers/nvidia-drivers-343.22-r2 and have trying  linux-3.12.21 and linux-3.16.5 with the same error. 

when I try running "optirun glxspheres64 -vvv" all I get is 

```
[ 2263.536258] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) NVIDIA(GPU-0): Failed to initialize the NVIDIA GPU at PCI:1:0:0.  Please
[ 2263.536319] [ERROR]Aborting because fallback start is disabled.
```

bumblebeed reports: 
```
[ 2263.533655] [DEBUG][XORG]Module class: X.Org XInput Driver
[ 2263.533661] [DEBUG][XORG]ABI class: X.Org XInput driver, version 20.0
[ 2263.533667] [DEBUG][XORG] (II) NVIDIA dlloader X Driver  343.22  Thu Sep 11 15:34:47 PDT 2014
[ 2263.533672] [DEBUG][XORG] (II) NVIDIA Unified Driver for all Supported NVIDIA GPUs
[ 2263.533677] [DEBUG][XORG] (--) using VT number 7
[ 2263.533682] [DEBUG][XORG] (II) Loading sub module "fb"
[ 2263.533687] [DEBUG][XORG] (II) LoadModule: "fb"
[ 2263.533692] [DEBUG][XORG] (II) Loading /usr/lib64/xorg/modules/libfb.so
[ 2263.533697] [DEBUG][XORG] (II) Module fb: vendor="X.Org Foundation"
[ 2263.533703] [DEBUG][XORG]compiled for 1.15.1, module version = 1.0.0
[ 2263.533709] [DEBUG][XORG]ABI class: X.Org ANSI C Emulation, version 0.4
[ 2263.533714] [DEBUG][XORG] (II) Loading sub module "wfb"
[ 2263.533719] [DEBUG][XORG] (II) LoadModule: "wfb"
[ 2263.533724] [DEBUG][XORG] (II) Loading /usr/lib64/xorg/modules/libwfb.so
[ 2263.533729] [DEBUG][XORG] (II) Module wfb: vendor="X.Org Foundation"
[ 2263.533734] [DEBUG][XORG]compiled for 1.15.1, module version = 1.0.0
[ 2263.533740] [DEBUG][XORG]ABI class: X.Org ANSI C Emulation, version 0.4
[ 2263.533746] [DEBUG][XORG] (II) Loading sub module "ramdac"
[ 2263.533751] [DEBUG][XORG] (II) LoadModule: "ramdac"
[ 2263.533755] [DEBUG][XORG] (II) Module "ramdac" already built-in
[ 2263.533760] [DEBUG][XORG] (II) NVIDIA(0): Creating default Display subsection in Screen section
[ 2263.533767] [DEBUG][XORG]"Default Screen" for depth/fbbpp 24/32
[ 2263.533772] [DEBUG][XORG] (==) NVIDIA(0): Depth 24, (==) framebuffer bpp 32
[ 2263.533778] [DEBUG][XORG] (==) NVIDIA(0): RGB weight 888
[ 2263.533783] [DEBUG][XORG] (==) NVIDIA(0): Default visual is TrueColor
[ 2263.533788] [DEBUG][XORG] (==) NVIDIA(0): Using gamma correction (1.0, 1.0, 1.0)
[ 2263.533793] [DEBUG][XORG] (**) NVIDIA(0): Option "NoLogo" "true"
[ 2263.533798] [DEBUG][XORG] (**) NVIDIA(0): Option "ProbeAllGpus" "false"
[ 2263.533803] [DEBUG][XORG] (**) NVIDIA(0): Option "UseEDID" "false"
[ 2263.533808] [DEBUG][XORG] (**) NVIDIA(0): Option "UseDisplayDevice" "none"
[ 2263.533813] [DEBUG][XORG] (**) NVIDIA(0): Enabling 2D acceleration
[ 2263.533818] [DEBUG][XORG] (**) NVIDIA(0): Ignoring EDIDs
[ 2263.533824] [DEBUG][XORG] (**) NVIDIA(0): Option "UseDisplayDevice" set to "none"; enabling NoScanout
[ 2263.533830] [DEBUG][XORG] (**) NVIDIA(0): mode
[ 2263.533843] [ERROR][XORG] (EE) NVIDIA(GPU-0): Failed to initialize the NVIDIA GPU at PCI:1:0:0.  Please
[ 2263.533851] [ERROR][XORG] (EE) NVIDIA(GPU-0): check your system's kernel log for additional error
[ 2263.533858] [ERROR][XORG] (EE) NVIDIA(GPU-0): messages and refer to Chapter 8: Common Problems in the
[ 2263.533864] [ERROR][XORG] (EE) NVIDIA(GPU-0): README for additional information.
[ 2263.533870] [ERROR][XORG] (EE) NVIDIA(GPU-0): Failed to initialize the NVIDIA graphics device!
[ 2263.533878] [ERROR][XORG] (EE) NVIDIA(0): Failing initialization of X screen 0
[ 2263.533883] [DEBUG][XORG] (II) UnloadModule: "nvidia"
[ 2263.533889] [DEBUG][XORG] (II) UnloadSubModule: "wfb"
[ 2263.533894] [DEBUG][XORG] (II) UnloadSubModule: "fb"
[ 2263.533899] [ERROR][XORG] (EE) Screen(s) found, but none have a usable configuration.
[ 2263.533905] [ERROR][XORG] (EE) 
[ 2263.533910] [DEBUG][XORG] Fatal server error:
[ 2263.533916] [ERROR][XORG] (EE) no screens found(EE) 
[ 2263.533921] [ERROR][XORG] (EE) 
[ 2263.533926] [DEBUG][XORG] Please consult the The X.Org Foundation support 
[ 2263.533931] [DEBUG][XORG] at http://wiki.x.org
[ 2263.533937] [DEBUG][XORG]  for help. 
[ 2263.533942] [ERROR][XORG] (EE) Please also check the log file at "/var/log/Xorg.8.log" for additional information.
[ 2263.533948] [ERROR][XORG] (EE) 
[ 2263.533954] [ERROR][XORG] (EE) Server terminated with error (1). Closing log file.
[ 2263.536142] [DEBUG]Process with PID 17427 returned code 1
[ 2263.536186] [ERROR]X did not start properly
[ 2263.536346] [DEBUG]Socket closed.
```

and the kernal log says:
```
Nov 25 17:15:29 dragon kernel: bbswitch: disabling discrete graphics
Nov 25 17:15:29 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:15:29 dragon kernel: pci 0000:01:00.0: Refused to change power state, currently in D0
Nov 25 17:15:59 dragon kernel: bbswitch: Unloaded. Discrete card 0000:01:00.0 is off
Nov 25 17:16:04 dragon kernel: bbswitch: version 0.8
Nov 25 17:16:04 dragon kernel: bbswitch: Found integrated VGA device 0000:00:02.0: \_SB_.PCI0.GFX0
Nov 25 17:16:04 dragon kernel: bbswitch: Found discrete VGA device 0000:01:00.0: \_SB_.PCI0.PEG0.PEGP
Nov 25 17:16:04 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:16:04 dragon kernel: bbswitch: detected an Optimus _DSM function
Nov 25 17:16:04 dragon kernel: bbswitch: Succesfully loaded. Discrete card 0000:01:00.0 is off
Nov 25 17:17:38 dragon kernel: bbswitch: enabling discrete graphics
Nov 25 17:17:38 dragon kernel: vgaarb: device changed decodes: PCI:0000:01:00.0,olddecodes=none,decodes=none:owns=none
Nov 25 17:17:38 dragon kernel: [drm] Initialized nvidia-drm 0.0.0 20130102 for 0000:01:00.0 on minor 1
Nov 25 17:17:38 dragon kernel: NVRM: loading NVIDIA UNIX x86_64 Kernel Module  343.22  Thu Sep 11 16:27:43 PDT 2014
Nov 25 17:17:38 dragon kernel: nvidia 0000:01:00.0: irq 47 for MSI/MSI-X
Nov 25 17:17:38 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:38 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:38 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:38 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:38 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:38 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:38 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:38 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:45 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:49 dragon kernel: NVRM: RmInitAdapter failed! (0x25:0x28:1193)
Nov 25 17:17:49 dragon kernel: NVRM: rm_init_adapter failed for device bearing minor number 0
Nov 25 17:17:49 dragon kernel: NVRM: nvidia_frontend_open: minor 0, module->open() failed, error -5
Nov 25 17:17:49 dragon kernel: nvidia 0000:01:00.0: irq 47 for MSI/MSI-X
Nov 25 17:17:49 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:49 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:49 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:49 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:49 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:49 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:49 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:49 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:49 dragon kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Nov 25 17:17:49 dragon kernel: NVRM: RmInitAdapter failed! (0x24:0x28:1167)
Nov 25 17:17:49 dragon kernel: NVRM: rm_init_adapter failed for device bearing minor number 0
Nov 25 17:17:49 dragon kernel: NVRM: nvidia_frontend_open: minor 0, module->open() failed, error -5
Nov 25 17:20:01 dragon crond[17437]: pam_unix(crond:session): session opened for user root by (uid=0)
Nov 25 17:20:01 dragon CROND[17439]: (root) CMD (test -x /usr/sbin/run-crons && /usr/sbin/run-crons )
Nov 25 17:20:01 dragon CROND[17437]: pam_unix(crond:session): session closed for user root
```

Any Idea was has been plaguing me for so long?

**Comment by ArchangeGabriel** [comment]
This should also be fixed with recent kernel (3.19 and above).

**Comment by hamechi** [comment]
I'm having this problem with kernel 3.19 and 640M LE, someone could help me?

**Comment by ArchangeGabriel** [comment]
@hamechi If you still have this issue, please paste dmesg.

**Comment by qwc** [comment]
Uhh, don't want to resurrect such an old issue, but it's still present on a brandnew DELL XPS 15 9560 (Intel i7 7700HQ, nvidia geforce 1050) with ArchLinux and Kernel 4.10.11

You do have a section in your troubleshooting wiki page with that kind of error message but no solution or further hints attached, so I searched for existing issues and found that one...

Here the output of your information script:
baseboard-manufacturer: Dell Inc.
baseboard-product-name: 05FFDN
baseboard-version     : A00
system-manufacturer   : Dell Inc.
system-product-name   : XPS 15 9560
system-version        : Not Specified
bios-vendor           : Dell Inc.
bios-version          : 1.0.3
bios-release-date     : 01/09/2017
