### ISSUE TITLE
(Xubuntu 16.04) Unloading or blacklisting nvidia modules causes xorg to freeze the system on start

### ISSUE THREAD

**Issue by TiZ-EX1** [Bumblebee-Project/Bumblebee#823]
Hi there. This is more of a tech support request to be frank. I figure you guys are the best ones to possibly know what to do. I just got a new laptop, with an optimus setup similar to my last one, except four generations newer. To be specific, the Gigabyte P55Wv6-NE2 with a 1060, up from my Asus G46VW with a 660M.

I'm using the nvidia drivers from the [graphics-drivers ppa](https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa), specifically nvidia-375. However, ever since 367 (maybe earlier?) the nvidia_modeset and nvidia_drm modules have been loaded up on boot, causing the card to get turned on. On my old laptop, I resolved this by blacklisting all the nvidia modules in modprobe.d. On my new laptop, this causes the system to totally freeze up any time xorg tries to start. Be it lightdm or startx in the console, same result. The framebuffer freezes up in whatever state it currently is in, and I can't use the system. When I check Xorg.0.log, I don't see anything abnormal. It's as if it doesn't even get to the point where it can log anything and just has stuff from the previous attempt.

Leaving the card on is unacceptable from a power management viewpoint, so I have to do something about it. So I figured I would just unload the modules and turn off the card after logging in. If I do that, I can still use optirun. But then I can't start a second X server, which I always do for games, because the same thing happens; the framebuffer freezes up and I can't use the system.

What would you all suggest I do next in pursuit of a fix for this issue?

**Comment by bluca** [comment]
Handling the multiple modules has been fixed in the devel branch, you can grab packages for 16.04 from the testing ppa

sudo add-apt-repository ppa:bumblebee/testing

https://launchpad.net/~bumblebee/+archive/ubuntu/testing

**Comment by TiZ-EX1** [comment]
Updating to the testing version of bumblebee has caused the Xorg freeze to manifest on startup when it tries to start lightdm. I'm presuming the testing version just has included blacklists for the drm and modeset modules? This doesn't fix my problem, it just forces it to happen.

**Comment by bluca** [comment]
The new modules are not blacklisted anywhere (and shouldn't be), the new version properly handles loading/unloading them via libkmod.

I see you are using 375, does it help adding:

```
blacklist nvidia-375
blacklist nvidia-375-updates
blacklist nvidia-experimental-375
```

At the bottom of /etc/modprobe.d/bumblebee.conf help? You need to run:

```
sudo depmod
sudo update-initramfs -u
```

And rebooting afterwards

**Comment by bluca** [comment]
Also I see it's a recent laptop, so it might be suffering from ACPI problems, see these tickets for more information and workarounds:

https://github.com/Bumblebee-Project/Bumblebee/issues/808
https://github.com/Bumblebee-Project/bbswitch/issues/140
https://github.com/Bumblebee-Project/bbswitch/issues/112

**Comment by TiZ-EX1** [comment]
#808 led me to a fix, namely adding `acpi_osi=! acpi_osi=\"Windows 2009\"` to the kernel params, in combination with bumblebee from testing. Thank you very much for your help. <3
