### ISSUE TITLE
error: [XORG] (EE) Failed to load module "mouse" (module does not exist, 0)

### ISSUE THREAD

**Issue by TeixeiraRafael** [Bumblebee-Project/Bumblebee#920]

**Comment by wagigi** [comment]
Same error on Debian 9. 

Was running and now not running.

**Comment by SanguisFerrum** [comment]
Same error. This happened after an upgrade. Not sure if it was a kernel or driver update.

**Comment by luishmelo** [comment]
Same error on Debian 9 and Nvidia 940MX

**Comment by mbacilieri** [comment]
Same here Ubuntu 16.04 and Nvidia 820M.
I'm pretty sure it's the kernel 4.4.x, for the 3.19.0-71 worked properly.

**Comment by Slowtechfr** [comment]
Same error on Debian 9 and Nvidia 1060. Can't even log in, screen freeze after entering password...
I tried everything but nothing is working, have you guys any solution ?

**Comment by jdcarvalho** [comment]
Same error here with Debian 9 and Nvidia 820M. Does anyone discovered a work around for this?

**Comment by mbacilieri** [comment]
After further investigation, I think it's in some way related to this: https://github.com/Bumblebee-Project/bbswitch/issues/160 . The problem happens in the same situation, and the cause is something in the relation between the kernel 4.x and the dkms of bbswitch.
I'm pretty sure the nvidia driver is not involved, for the error happens with nouveau too.
For now, the only solutions I found are:

1. to keep a 3.19 kernel which works, although not completely (I can't use bluetooth);
2. to use only the integrated card ("intel") using the nvidia driver in "intel" mode (prime-select intel) and never use the discrete card.

There are no further way to me to use a 4.x kernel: last shipped by Ubuntu is the 4.4.0-104 which continue to have the same problem.

**Comment by marcosValle** [comment]
Nothing yet?? =/

**Comment by ClaytonMcCray** [comment]
Same issue with Debian 9 and Quadro M520 except that I'm not entirely sure if my setup was every fully operational since I only recently cared about the discrete card.

**Comment by edgyer** [comment]
same error on debian 9 here... not sure if it was working before as well... any news?

**Comment by VlijmenFileer** [comment]
Same here.  I have not (yet) found any solution.  Does that mean that bumblebee is now non-functional?

1)    Clean Debian 9 installation.  Neofetch output :
OS: Debian GNU/Linux 9.3 (stretch) x86_64
Model: Dell System XPS L502X 
Kernel: 4.9.0-5-amd64 
Resolution: 1920x1080 
DE: XFCE 
CPU: Intel i5-2520M (4) @ 3.2GHz 
GPU: NVIDIA GeForce GT 525M 
Memory: 2042MB / 7881MB 

2)    Nvidia support installation as per: https://wiki.debian.org/Bumblebee :
apt-get install bumblebee primus
2a)  Versions :
apt show bumblebee primus | grep -A1 "Package: " :
Package: bumblebee
Version: 3.2.1-14
Package: primus
Version: 0~20150328-4

3) Graphics controllers: lspci -k -d ::0300 :
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
	Subsystem: Dell 2nd Generation Core Processor Family Integrated Graphics Controller
	Kernel driver in use: i915
	Kernel modules: i915
01:00.0 VGA compatible controller: NVIDIA Corporation GF108M [GeForce GT 525M] (rev a1)
	Subsystem: Dell GF108M [GeForce GT 525M]
	Kernel driver in use: nouveau
	Kernel modules: nouveau

**Comment by VlijmenFileer** [comment]
Same here.  I have not (yet) found any solution.  Does that mean that bumblebee is now non-functional?

1)    Clean Debian 9 installation.  Neofetch output :
OS: Debian GNU/Linux 9.3 (stretch) x86_64
Model: Dell System XPS L502X 
Kernel: 4.9.0-5-amd64 
Resolution: 1920x1080 
DE: XFCE 
CPU: Intel i5-2520M (4) @ 3.2GHz 
GPU: NVIDIA GeForce GT 525M 
Memory: 2042MB / 7881MB 

2)    Nvidia support installation as per: https://wiki.debian.org/Bumblebee :
apt-get install bumblebee primus
2a)  Versions :
apt show bumblebee primus | grep -A1 "Package: " :
Package: bumblebee
Version: 3.2.1-14
Package: primus
Version: 0~20150328-4

3) Graphics controllers: lspci -k -d ::0300 :
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
	Subsystem: Dell 2nd Generation Core Processor Family Integrated Graphics Controller
	Kernel driver in use: i915
	Kernel modules: i915
01:00.0 VGA compatible controller: NVIDIA Corporation GF108M [GeForce GT 525M] (rev a1)
	Subsystem: Dell GF108M [GeForce GT 525M]
	Kernel driver in use: nouveau
	Kernel modules: nouveau

4) dmesg manually output that seemed possibly interesting:
[    0.248481] vgaarb: setting as boot device: PCI:0000:00:02.0
[    0.248482] vgaarb: device added: PCI:0000:00:02.0,decodes=io+mem,owns=io+mem,locks=none
[    0.248486] vgaarb: device added: PCI:0000:01:00.0,decodes=io+mem,owns=none,locks=none
[    0.248487] vgaarb: loaded
[    0.248487] vgaarb: bridge control possible 0000:01:00.0
[    0.248488] vgaarb: no bridge control possible 0000:00:02.0
[    0.258458] system 00:02: [io  0x0454-0x0457] has been reserved
[    0.258460] system 00:02: Plug and Play ACPI device, IDs INT3f0d PNP0c02 (active)
[    0.265214] pci 0000:01:00.0: can't claim BAR 6 [mem 0xfff80000-0xffffffff pref]: no compatible bridge window
[    0.265261] pci 0000:01:00.0: BAR 6: assigned [mem 0xf1000000-0xf107ffff pref]
[    9.715329] i915 0000:00:02.0: fb0: inteldrmfb frame buffer device
[   18.116343] bbswitch: Found integrated VGA device 0000:00:02.0: \_SB_.PCI0.GFX0
[   18.116355] bbswitch: Found discrete VGA device 0000:01:00.0: \_SB_.PCI0.PEG0.PEGP
[   18.116381] ACPI Warning: \_SB.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20160831/nsarguments-95)
[   18.116853] bbswitch: detected an Optimus _DSM function
[   18.116875] pci 0000:01:00.0: enabling device (0006 -> 0007)
[   18.116958] bbswitch: Succesfully loaded. Discrete card 0000:01:00.0 is on
[   18.118418] bbswitch: disabling discrete graphics
[  522.928583] bbswitch: enabling discrete graphics
[  523.599177] ACPI Warning: \_SB.PCI0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20160831/nsarguments-95)
[  523.599373] ACPI Warning: \_SB.PCI0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20160831/nsarguments-95)
[  523.599545] i915 0000:00:02.0: optimus capabilities: enabled, status dynamic power, hda bios codec supported
[  523.599581] ACPI Warning: \_SB.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20160831/nsarguments-95)
[  523.599738] ACPI Warning: \_SB.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20160831/nsarguments-95)
[  523.599883] pci 0000:01:00.0: optimus capabilities: enabled, status dynamic power, hda bios codec supported
[  523.599888] VGA switcheroo: detected Optimus DSM method \_SB_.PCI0.PEG0.PEGP handle
[  523.600034] nouveau 0000:01:00.0: NVIDIA GF108 (0c1a80a1)
[  523.649259] nouveau 0000:01:00.0: bios: version 70.08.53.00.04
[  523.744981] nouveau 0000:01:00.0: fb: 512 MiB DDR3
[  523.795447] vga_switcheroo: enabled
[  523.795776] [TTM] Zone  kernel: Available graphics memory: 4035194 kiB
[  523.795777] [TTM] Zone   dma32: Available graphics memory: 2097152 kiB
[  523.795778] [TTM] Initializing pool allocator
[  523.795782] [TTM] Initializing DMA pool allocator
[  523.795809] nouveau 0000:01:00.0: DRM: VRAM: 512 MiB
[  523.795809] nouveau 0000:01:00.0: DRM: GART: 1048576 MiB
[  523.795812] nouveau 0000:01:00.0: DRM: TMDS table version 2.0
[  523.795813] nouveau 0000:01:00.0: DRM: DCB version 4.0
[  523.795815] nouveau 0000:01:00.0: DRM: DCB outp 00: 02014300 00000000
[  523.795816] nouveau 0000:01:00.0: DRM: DCB outp 01: 02021362 00020010
[  523.795817] nouveau 0000:01:00.0: DRM: DCB conn 00: 00000340
[  523.795818] nouveau 0000:01:00.0: DRM: DCB conn 01: 00001061
[  523.795818] nouveau 0000:01:00.0: DRM: DCB conn 02: 00000147
[  523.795819] nouveau 0000:01:00.0: DRM: DCB conn 03: 00002346
[  523.795820] nouveau 0000:01:00.0: DRM: DCB conn 04: 00000400
[  523.795820] nouveau 0000:01:00.0: DRM: DCB conn 05: 00000210
[  523.795821] nouveau 0000:01:00.0: DRM: DCB conn 06: 00000211
[  523.795822] nouveau 0000:01:00.0: DRM: DCB conn 07: 00000213
[  523.797958] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[  523.797959] [drm] Driver supports precise vblank timestamp query.
[  523.850199] nouveau 0000:01:00.0: DRM: MM: using COPY0 for buffer copies
[  523.910212] nouveau 0000:01:00.0: DRM: allocated 1024x768 fb: 0x60000, bo ffff8d0e3bc6b000
[  523.910314] nouveau 0000:01:00.0: fb1: nouveaufb frame buffer device
[  523.910331] [drm] Initialized nouveau 1.3.1 20120801 for 0000:01:00.0 on minor 1
[  530.591462] ACPI Warning: \_SB.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20160831/nsarguments-95)
[  530.591870] ACPI Warning: \_SB.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20160831/nsarguments-95)
[  530.592162] nouveau 0000:01:00.0: DRM: suspending console...
[  530.592166] nouveau 0000:01:00.0: DRM: suspending display...
[  530.592183] nouveau 0000:01:00.0: DRM: evicting buffers...
[  530.649821] nouveau 0000:01:00.0: DRM: waiting for kernel channels to go idle...
[  530.649851] nouveau 0000:01:00.0: DRM: suspending client object trees...
[  530.650112] nouveau 0000:01:00.0: DRM: suspending kernel object tree...

**Comment by edgyer** [comment]
@VlijmenFileer so, after posting here I tried a whole bunch of distros, from ubuntu, parrotOS to steamOS, the one that worked best with bumblebee + nvidia (not nouveau) was arch linux, I think that bumblebee on debian 9 has some sort of compatibility issue, a really bad one at that. Maybe it's something kernel related. Unfortunately I gave up and had to go to arch.

**Comment by unixusers** [comment]
I ran into the same problem after a clean install on my Dell Inspiron 7537.
After installing xserver-xorg-input-mouse, I get the following error (snippet from my dmesg):

[  433.685562] bbswitch: version 0.8
[  433.685565] bbswitch: Found integrated VGA device 0000:00:02.0: \_SB_.PCI0.GFX0
[  433.685567] bbswitch: Found discrete VGA device 0000:04:00.0: \_SB_.PCI0.RP05.PXSX
[  433.685575] bbswitch: failed to evaluate \_SB_.PCI0.RP05.PXSX._DSM {0xF8,0xD8,0x86,0xA4,0xDA,0x0B,0x1B,0x47,0xA7,0x2B,0x60,0x42,0xA6,0xB5,0xBE,0xE0} 0x100 0x0 {0x00,0x00,0x00,0x00}: AE_NOT_FOUND
[  433.685579] bbswitch: failed to evaluate \_SB_.PCI0.RP05.PXSX._DSM {0xA0,0xA0,0x95,0x9D,0x60,0x00,0x48,0x4D,0xB3,0x4D,0x7E,0x5F,0xEA,0x12,0x9F,0xD4} 0x102 0x0 {0x00,0x00,0x00,0x00}: AE_NOT_FOUND
[  433.685586] ACPI Warning: \_SB.PCI0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20160831/nsarguments-95)
[  433.685626] bbswitch: No suitable _DSM call found.

@Inspiron-7537:~$  optirun glxgears
[ 1556.432163] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) NVIDIA(GPU-0): Failed to initialize the NVIDIA GPU at PCI:4:0:0.  Please

[ 1556.432192] [ERROR]Aborting because fallback start is disabled.

Searching here for similar errors/issues, I found the following problems in bbswitch for both drivers, nvidia and nouveau:
https://github.com/Bumblebee-Project/bbswitch/issues/160
https://github.com/Bumblebee-Project/bbswitch/issues/151

There might be a bug in the kernel using bbswitch. The solution in one of the issue posts given above is using a newer kernel. In debian you can easily install annd use a backports kernel. The following steps solved the problem for me:

Add the following line to your /etc/apt/sources.list
deb http://ftp.debian.org/debian stretch-backports main contrib non-free contrib

sudo apt-get -t stretch-backports install linux-image-amd64 linux-headers-4.14.0-0.bpo.3-amd64
sudo reboot
sudo apt-get -t stretch-backports install nvidia-driver
sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install bbswitch-dkms bumblebee bumblebee-nvidia primus primus-libs:i386

Follow the instructions on the debian wiki page for user groups and setting up your bumblebee configuration file depending on your driver (free/non-free)

If you have a previously installed the default  nvidia driver package from the stretch repository, you have to uninstall the driver first and than following the steps above:
sudo apt-get remove nvidia-driver
sudo apt-get autoremove

**Comment by TeixeiraRafael** [comment]
That worked for me! Thank you so much!

**Comment by Alejandroem** [comment]
I managed to fix this issue by installing this package
https://packages.debian.org/search?keywords=xserver-xorg-input-mouse

Then i just fixed the bus id in the /etc/bumblebee/xorg.conf.nvidia you can find your bus id by running lspci | egrep 'VGA|3D'

**Comment by cemysf** [comment]
hi, is this problem resolved with newer kernel, or should we still use the backport kernel?

**Comment by fernando-jascovich** [comment]
After installaing xserver-xorg-input-mouse, I was getting the following error:
> Screen 0 deleted because of no matching config section

There are two modifications needed at `/etc/bumblebee/xorg.conf.nvidia` in order to get optirun to work:
* Uncomment "BusID" at Device section and put the right id (the value can be obtained from `lspci`)
* Add this snippet at the end of the file:
```
     Section "Screen"
         Identifier "Default Screen"
         Device "DiscreteNvidia"
     EndSection
```

After that, and after restarting systemd service I got optirun working on ubuntu 18.04 (server)

**Comment by sserdyuk1991** [comment]
Please consider #867 as duplicate.

In my case (Debian 9, GeForce GT 525M, nouveau driver) the issue was resolved by adding mentioned above "Screen" section to `/etc/bumblebee/xorg.conf.nouveau`.

However I got another issue:
[ERROR]Cannot access secondary GPU - error: [XORG] (EE) NOUVEAU(0): [drm] failed to set drm interface version.

**Comment by deven96** [comment]
> Please consider #867 as duplicate.
> 
> In my case (Debian 9, GeForce GT 525M, nouveau driver) the issue was resolved by adding mentioned above "Screen" section to `/etc/bumblebee/xorg.conf.nouveau`.
> 
> However I got another issue:
> [ERROR]Cannot access secondary GPU - error: [XORG] (EE) NOUVEAU(0): [drm] failed to set drm interface version.

I also squashed the mouse error fixed by installing the xserver-xorg-input-mouse issue but then it led to the failed to set drm interface version. Is there any way you solved it @sserdyuk1991

**Comment by DavidGriffith** [comment]
This bug still exists.  I'm running Debian 11 with a Quadro NVS 4200M.  It is sort of fixed with the suggestions above, but now I see this:

````
$ optirun glxgears
[ 1282.334752] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) Failed to load module "glx" (module does not exist, 0)

[ 1282.334791] [ERROR]Aborting because fallback start is disabled.
````
But the `glx` module is in `/usr/lib/xorg/modules/` and I've set `XorgModulePath=/usr/lib/nvidia:/usr/lib/xorg/modules` in the `[driver-nvidia]` section.  This was enough to get the complaints about the mouse module not existing, but not for the glx module.
